#!/bin/sh
set -e
cd $(dirname "$0")

CONFIG_FILE=/usr/local/etc/xray/config.json

if [ "0" != "$(id -u)" ]; then
  vim -R ${CONFIG_FILE}
  exit 0
fi

edit_time()
{
  echo $(stat --format=%Y ${CONFIG_FILE})
}

LAST_EDIT_TIME=$(edit_time)
vim ${CONFIG_FILE}

if [[ ${LAST_EDIT_TIME} -eq $(edit_time) ]]; then
  exit 0
fi
systemctl restart xray
journalctl -fu xray
